services:
  db:
    image: postgres:15-alpine
    container_name: book_library_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"   # keep only if you need external access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    container_name: book_library_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: book_library_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: