# Generated by Django 5.2.6 on 2025-09-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_available_copies_remove_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn__gt', '')), fields=('isbn',), name='unique_non_empty_isbn'),
        ),
    ]
